version: "3.2"
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: "ms_vagr:gateway"
    volumes:
      - "./gateway/node_modules:/home/node/app/node_modules"
      - "./gateway/.env:/home/node/app/.env"
      - "./gateway:/home/node/app"
    env_file:
      - ./gateway/.env
    ports:
      - 3001:3001

  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    image: "ms_vagr:product"
    volumes:
      - "./product/node_modules:/home/node/app/node_modules"
      - "./product/.env:/home/node/app/.env"
      - "./product:/home/node/app"
    env_file:
      - ./product/.env
    ports:
      - 3002:3002

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: "ms_vagr:user"
    volumes:
      - "./user/node_modules:/home/node/app/node_modules"
      - "./user/.env:/home/node/app/.env"
      - "./user:/home/node/app"
    env_file:
      - ./user/.env
    ports:
      - 3003:3003

networks:
  ms_vagr:
    external: true
