version: "3.2"
services:
  appmain:
    build:
      context: ./app_main
      dockerfile: Dockerfile
    image: "ms_vagr:appmain"
    volumes:
      - "./app_main/node_modules:/home/node/app/node_modules"
      - "./app_main:/home/node/app"
    ports:
      - 5000:3000

  appone:
    build:
      context: ./app_one
      dockerfile: Dockerfile
    image: "ms_vagr:appone"
    volumes:
      - "./app_one/node_modules:/home/node/app/node_modules"
      - "./app_one:/home/node/app"
    ports:
      - 5001:3000

  apptwo:
    build:
      context: ./app_two
      dockerfile: Dockerfile
    image: "ms_vagr:apptwo"
    volumes:
      - "./app_two/node_modules:/home/node/app/node_modules"
      - "./app_two:/home/node/app"
    ports:
      - 5002:3000

  appthree:
    build:
      context: ./app_three
      dockerfile: Dockerfile
    image: "ms_vagr:appthree"
    volumes:
      - "./app_three/node_modules:/home/node/app/node_modules"
      - "./app_three:/home/node/app"
    ports:
      - 5003:3000

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: "ms_vagr:gateway"
    volumes:
      - "./gateway/node_modules:/home/node/app/node_modules"
      - "./gateway/.env:/home/node/app/.env"
      - "./gateway:/home/node/app"
    env_file:
      - ./gateway/.env
    ports:
      - 5004:3001

  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    image: "ms_vagr:product"
    volumes:
      - "./product/node_modules:/home/node/app/node_modules"
      - "./product/.env:/home/node/app/.env"
      - "./product:/home/node/app"
    env_file:
      - ./product/.env
    ports:
      - 5005:3002

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: "ms_vagr:user"
    volumes:
      - "./user/node_modules:/home/node/app/node_modules"
      - "./user/.env:/home/node/app/.env"
      - "./user:/home/node/app"
    env_file:
      - ./user/.env
    ports:
      - 5006:3003

  selenoid:
    build:
      context: ./docker/selenoid
      dockerfile: Dockerfile
    image: "ms_vagr:selenoid"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/selenoid/config/:/etc/selenoid/:ro"
      - "./docker/selenoid/logs/:/opt/selenoid/logs"
    env_file:
      - ./docker/selenoid/.env
    ports:
      - 5007:4444

  selenoid-ui:
    image: "aerokube/selenoid-ui:1.10.4"
    links:
      - selenoid
    ports:
      - "5008:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
